config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :dishes
    member do
      get 'remove_guest'
      post 'remove_guest'
    end
  end

  resources :users
    
  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/users/:user_id/events/new' => 'events#new'
  get '/users/:user_id/events/:id' => 'events#show'
  get '/events/:event_id/dishes/:id/bring_dish' => 'events#dish_form'
  post '/events/:event_id/dishes/:id/bring_dish' => 'events#bring_dish'
  post '/events/:id/add_guest' => 'events#add_guest'
  

end

app/models/user.rb
require 'bcrypt'

# Stores User information as host and/or as guest.
class User < ActiveRecord::Base
  has_many :invitations
  has_many :hosted_events, class_name: 'Event', foreign_key: :event_id, through: :invitations
  has_many :attending_events, class_name: 'Event', foreign_key: :event_id, through: :invitations
  has_many :dishes
  # has_many :dietary_restrictions
  validates :name, :password_hash, :email, :phone, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 2, too_short: 'Name is too short (minimum is 2 characters)' }
  validates :password_hash, length: { minimum: 5, too_short: 'Password is too short (minimum is 5 characters)' }
  validate :name_valid?
  # validates :email, format: { with: /\S+@\w+.\w+/, message: 'please enter a valid email' }
  validate :phone_valid?
  validates_with EmailAddress::ActiveRecordValidator, field: :email
  # accepts_nested_attributes_for :dietary_restrictions

  def name_valid?
    errors.add(:name, 'Name is not capitalized') if name.scan(/\A[A-Z]/).empty?
  end

  def phone_valid?
    if phone.scan(/\d/).size != 10
      errors.add(:phone, 'Phone number needs to have 10 digits')
    end
  end

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def attending
    attending_all = attending_events
    attending = []
    attending_all.each do |event|
      attending << event unless event.host == self
    end
  end
end

app/controllers/users_controller.rb
# Handles http requests for User model.
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events_attending = []
    @events_hosting = []
    @user.attending_events.each do |event|
      if event.host.id == @user.id
        @events_hosting << event
      else
        @events_attending << event
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    # @user.password = params[:user][:password_hash]
    # @user.password = params[:password]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :password_hash, :email, :phone)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.phone_field :phone %>
  </div>
  <div class="field">
    <%= f.label 'Password' %>
    <%= f.password_field :password_hash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<% if logged_in? %>
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %>
        <% if current_user == user %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <h4>Please log in to view User List.</h4>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @user.name %>'s Events</h1>
<h3>Hosting:</h3>
	<% if !@events_hosting.empty? %>
		<% @events_hosting.each do |hosted| %>
		<table>
			<tr>
				<td><%= link_to hosted.name, "/users/#{@user.id}/events/#{hosted.id}" %></td>
			</tr>
		<% end %>
		</table>
	<% else %>
		<p>No events to show.</p>
	<% end %>
	<% if logged_in? && @user == current_user %>
		<p><%= link_to 'Create New Event', "/users/#{@user.id}/events/new" %></p>
	<% end %>
</br>
<h3>Attending:</h3>
	<% if !@events_attending.empty? %>
		<% @events_attending.each do |attending| %>
		<table>
			<tr>
				<td><%= link_to attending.name, event_path(attending) %></td>
			</tr>
			<% end %>
		</table>
	<% else %>
		<p>No events to show.</p>
	<% end %>
</br>
<%= link_to 'Edit Profile', edit_user_path(@user) %> |
<%= link_to 'Back to Users', users_path %>