config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :dishes
    member do
      get 'remove_guest'
      post 'remove_guest'
    end
  end

  resources :users
    
  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/users/:user_id/events/new' => 'events#new'
  get '/users/:user_id/events/:id' => 'events#show'
  get '/events/:event_id/dishes/:id/bring_dish' => 'events#dish_form'
  post '/events/:event_id/dishes/:id/bring_dish' => 'events#bring_dish'
  post '/events/:id/add_guest' => 'events#add_guest'
  

end

app/models/event.rb
# Stores Event information including guest and dish lists.
class Event < ActiveRecord::Base
  has_many :invitations
  has_many :guests, class_name: 'User', through: :invitations
  has_many :dishes
  belongs_to :host, class_name: 'User', foreign_key: :user_id
  accepts_nested_attributes_for :dishes
  validates :name, :start_time, :end_time, :street1, :city, presence: true
  validates :name, length: { minimum: 2, too_short: 'Event name is too short (minimum is 2 characters)' }

  # Returns a list of possible guests (not the host, not already attending) for guest_form.
  def possible_guests
    guests.each do |guest|
      @possible = User.all.reject { |user| user.id == guest.id || user.id == host.id }
    end
    @possible
  end

  # Helper method for event#remove_guest.
  def remove(guest)
    remove_dishes(guest)
    guests.delete(guest)
    guest.attending_events.delete(self)
  end

  # Helper method for remove method.
  def remove_dishes(guest)
    guest.dishes.each do |dish|
      dish.update(user_id: host.id) if dish.user_id == guest.id
      dish.increment_quantity
    end
  end

  # List dishes_needed in drop-down menu, if impletmented.
  def dishes_needed
    dishes_requested = host.dishes
    dishes_needed = []
    dishes_requested.each do |dish|
      dishes_needed << dish if dish.user_id == host.id
    end
  end
end

app/controllers/events_controller.rb
# Handles http requests for Event model.
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :add_guest]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  def new
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @possible = @event.possible_guests
  end

  def add_guest
    @event = Event.find(params[:id])
    @guest = User.find(params[:event][:user_id])
    @guest.attending_events.append @event
    redirect_to event_path(@event), notice: "#{@guest.name} was successfully added to the guest list."
  end

  # POST /events/1/remove_guest?event_id=1&user_id=3
  def remove_guest
    @event = Event.find(params[:event_id])
    @guest = User.find(params[:user_id])
    @event.remove(@guest)
    redirect_to event_path(@event), notice: "#{@guest.name} was successfully removed from the guest list."
  end

  def dish_form
    @event = Event.find(params[:event_id])
    @dish = Dish.find(params[:id])
  end

  # POST /events/1/bring_dish?dish_id=6&event_id=1
  def bring_dish
    @event = Event.find(params[:event_id])
    @dish = Dish.find(params[:id])
    @dish.update(dish_params)
    @guest = User.find(current_user.id)
    @guest.dishes << @dish
    @dish.decrement_quantity
    redirect_to event_path(@event), notice: 'You have successfully claimed a dish.'
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.host = current_user

    respond_to do |format|
      if @event.save
        current_user.hosted_events.append @event
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :location, :date, :start_time,
                                  :end_time, :notes, :street1, :street2,
                                  :city, :state, :zip_code, :country)
  end

  def dish_params
    params.require(:dish).permit(:event_id, :user_id, :name, :description,
                                 :quantity, :servings, :user_name,
                                 :quantity_needed, :quantity_requested)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.hidden_field :user_id %>
  </div>
  <div class="field">
    <%= f.label 'Event Name' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f. label :start_time %>
    <%= f.datetime_select 'start_time' %>
  </div>
  <div class="field">
    <%= f. label :end_time %>
    <%= f.datetime_select 'end_time' %>
  </div>
    <div class="field">
    <%= f.label 'Event Location' %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label 'Street 1' %>
    <%= f.text_field :street1 %>
  </div>
  <div class="field">
    <%= f.label 'Street 2' %>
    <%= f.text_field :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_guest_form.html.erb
<%= form_for(@event, url: "/events/#{@event.id}/add_guest", method: :post) do |f| %>
	<div class="field">
		<%= f.collection_select(:user_id, @possible, :id, :name, {prompt: 'Please Select' }) %>
	</div>

	<div class="actions">
		<%= f.submit 'Add Guest' %>
	</div>
<% end %>

app/views/events/dish_form.html.erb
<%= form_for([@event, @dish], url: "/events/#{@event.id}/dishes/#{@dish.id}/bring_dish", method: :post) do |f| %>
	<!--<div class="field">
		<%#= f.collection_select(:dish_id, @event.dishes, :id, :name, prompt: true) %>
	</div>-->
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	<div>
  		<%#= f.hidden_field :event_id %>
  		<%#= f.hidden_field :dish_id %>
  		<%= f.hidden_field :user_id %>
  	</div>
  	<div class="field">
    	<%= f.label :name %> <%= @dish.name %>
  	</div>
  	<div class="field">
    	<%= f.label :description %>
    	<%= f.text_area :description %>
  	</div>
  	<div class="field">
  		<p>Quantity Needed = <%= @dish.quantity_needed %></p>
    	<%= f.label :quantity %>
    	<%= f.text_field :quantity %>
  	</div>
  	<div class="field">
    	<%= f.label :servings %>
    	<%= f.text_field :servings %>
  	</div>
	<div class="actions">
		<%= f.submit 'Bring Dish' %>
	</div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @event.name %> Details:</h1>
<table>
	<tr><td><b>Date: </b></td><td><%= @event.start_time.strftime("%A, %B %-d, %Y") %></td></tr>
	<tr><td><b>Time: </b></td><td><%= @event.start_time.strftime("%-I:%M%P") %> - <%= @event.end_time.strftime("%-I:%M%P") %></td></tr>
	<tr><td><b>Location: </b></td><td><%= @event.location %></td></tr>
	<tr><td></td><td><%= @event.street1 %></td></tr>
	<tr><td></td><td><%= @event.street2 %></td></tr>
	<tr><td></td><td><%= @event.city %>, <%= @event.state%> <%= @event.zip_code %></td></tr>
	<tr><td><b>Notes: </b></td><td><%= @event.notes %></td></tr>
	<tr><td><b>Guests: </b></td><td><%= @event.guests.length %></td></tr>
</table>
<% if logged_in? && @event.host.id == current_user.id %>
	<p><%= link_to 'Edit Event', edit_event_path(@event) %></p>
<% end %>
</br>
<h3>The Guest List</h3>
	<% if @event.guests.empty? %>
		<p>There are no guests for this event.</p>
	<% else %>
		<table>
		<% @event.guests.each do |guest| %>
			<tr>
				<td><%= guest.name.upcase %>  
				<% if guest.id == @event.host.id %>
					(host)
				<% end %>
				<% unless guest.id == @event.host.id %>
					<% if logged_in? && @event.host.id == current_user.id %>
					<%= link_to 'Remove Guest', { :action => :remove_guest, :controller => 'events', :event_id => @event.id, :user_id => guest.id } %></td>
					<% end %>
				<% end %>
			</tr>
			<tr>
				<% unless guest.dishes.empty? %>
					<% guest.dishes.each do |dish| %>
						<% unless dish.user_id == @event.host.id %>
							<tr>
								<td>&nbsp&nbsp<%= dish.name %>: <%= dish.description %> (Qty <%= dish.quantity%>)</td>
							</tr>
						<% end %>
					<% end %>
				<% end %>
			</tr>
		<% end %>
		</table>
	<% end %>
	</br>

	<% if logged_in? && @event.host == current_user %>
		<%= render 'guest_form' %>
	</br>
	<% end %>

<h3>The Dish List</h3>
<% if @event.dishes.empty? %>
	<p>There are no dishes for this event.</p>
<% else %>
	<% @event.dishes.each do |dish| %>
		<table>
			<tr>
				<td><%= dish.name.upcase %></td>
				<% if logged_in? %>
				 	<% if @event.host == current_user %>
						<td><%= link_to 'Edit Dish', edit_event_dish_path(@event, dish) %></td>
						<td><%= link_to 'Remove Dish', "/events/#{@event.id}/dishes/#{dish.id}", method: :delete %></td>
					<% else %>
						<% unless dish.quantity_needed == 0 %>
						<td><%= link_to 'Bring it!', "/events/#{@event.id}/dishes/#{dish.id}/bring_dish" %></td>
						<% end %>
					<% end %>
				<% end %>
 			</tr>
			<tr>
				<td>&nbsp&nbspQuantity Requested = <%= dish.quantity_requested %> | </td>
				<td>Quantity Needed = <%= dish.quantity_needed %></td>
			</tr>
			<tr></tr>
		</table>
	<% end %>
	</br>
<% end %>
	<% if logged_in? && @event.host == current_user %>
		<%= link_to 'Add Dish to Menu', new_event_dish_path(@event) %>
	</br>
	<% end %>
</br>
<%= link_to 'Edit Event', edit_event_path(@event) %> |
<%= link_to "Back to #{current_user.name}'s Homepage", user_path %>